language: cpp

os:
- osx
- linux

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install qt5; fi
  
compiler:
  # - clang
  - gcc
  
script:
  - mkdir build
  - cd build
  - cmake .. -DWITH_SNORE_DAEMON=ON -DWITH_FRONTENDS=ON
  - make

addons:
  apt:
    packages:
    - cmake
    - qtbase5-dev
    - qtquick1-5-dev
    - qttools5-dev
    