version: '{build}'
branches:
  only:
    - master
    - ci
    
build_script:
    - ps: if ( !(Test-Path "$env:APPVEYOR_BUILD_FOLDER\ci\appveyorHelp.psm1")) {Start-FileDownload https://raw.githubusercontent.com/TheOneRing/appVeyorHelp/master/appveyorHelp.psm1 -FileName $env:APPVEYOR_BUILD_FOLDER\ci\appveyorHelp.psm1 }
    - ps: .\ci\appveyor.ps1

test: off

cache:
    - work\git -> ci\appveyor.ps1
    - work\install -> ci\appveyor.ps1
    - C:\ProgramData\chocolatey\bin -> ci\appveyor.ps1
    - C:\ProgramData\chocolatey\lib -> ci\appveyor.ps1
    - C:\tools -> ci\appveyor.ps1
    - ci\appveyorHelp.psm1 -> ci\appveyor.ps1

environment:
    SNORE_TOASTY_ID:
        secure: lh3yt2ig14pCQMkJ9FRUj4dRLp+pw8qpLgoxr1t8Tpyo27JqXOhYMtGnZPI3wf/S
        
    SNORE_PUSHOVER_KEY:
        secure: KTJ5xlUJfDSxpzaGLsnTDhVa2jxWkzaEcwlI2MGCn4g=
        
    FETCH_ARTIFATCS_HOST:
        secure: rMU3uKmS1tdIFReTTcRgchX2PJaOKSXc72lIG6OOR3RPR3Nhc8hjNnti2+WM52Ei9hsq/QMEsQaWEOFMLrvPPw==
        
    QT_VER: 5.5
    
    matrix:
    #mingw
    - COMPILER: mingw492_32
    #msvc
    - COMPILER: msvc2013_64
    
artifacts:
    - path: work\image
      name: $(APPVEYOR_PROJECT_NAME)-Qt$(QT_VER)-$(COMPILER)
    - path: work\log
      name: log-$(APPVEYOR_PROJECT_NAME)-Qt$(QT_VER)-$(COMPILER)
      
deploy:
    - provider: Environment
      name: my
      